# Generated by Django 3.2.5 on 2021-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20210807_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Processing', 'processing'), ('Delivering', 'delivering'), ('Delivered', 'delivered'), ('Not Delivered', 'not_delivered')], default='Processing', max_length=50),
        ),
    ]
